### ISSUE TITLE
Domain auth flow

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/app-google-analytics#12]
- Authentication needs to be separated from domain selection.
- Authentication should be checked by using a separate google lookup, if authentication fails the authentication button should show. 
- If authentication exists, and there is no profile ID selected, a popup giving the user an option to select from their GA properties should appear. 
- The user should be given an option to reselect their domain which will restart the GA domain selection interface
- Display a return error message 

Experience:
1. If no authentication exists, the current experience with the "Click to Authenticate" button should show
2. If authentication exists, but no domain, a popup modal that displays all GA properties (from the GA endpoint) to select from, or manually enter the GA ID's to authenticate

**Comment by allenpigar** [comment]
added domain selection.
https://github.com/zesty-io/app-google-analytics/pull/13

**Comment by allenpigar** [comment]
![image](https://user-images.githubusercontent.com/50983144/176748982-3e09d95d-23a4-4c93-bab9-8898f9c072ba.png)

![image](https://user-images.githubusercontent.com/50983144/176749095-eb8f61a9-f877-47dd-89c7-bed20bd8df51.png)
