### ISSUE TITLE
On choose domain pop, add helpder text disclaimer

### ISSUE THREAD

**Issue by ardeay** [zesty-io/app-google-analytics#15]
`Choosing a domain will update your google profile id, google accounts id, and google urchin id (legacy). This change updates production when your cache is refreshed.`

**Comment by allenpigar** [comment]
Added disclaimer.

![image](https://user-images.githubusercontent.com/50983144/177197118-0ff661bc-56e5-4e4f-abd0-7a7ee9621611.png)
