### ISSUE TITLE
domain selection button

### ISSUE THREAD

**Issue by ardeay** [zesty-io/app-google-analytics#16]
![image](https://user-images.githubusercontent.com/729972/176920017-dbe07454-4b15-4329-84f0-4a3df6c10443.png)

If a domain is already selected, button should say "change domain", if no domain is selected, it should say "select domain"

**Comment by allenpigar** [comment]
Header when there is no selected domain.

![image](https://user-images.githubusercontent.com/50983144/177197006-50fdd984-f7ed-45b6-abd0-a9fb36c5774e.png)

Header with selected domain.

![image](https://user-images.githubusercontent.com/50983144/177197041-d6dfa946-764b-4c55-a3aa-0aacbaf75484.png)
