### ISSUE TITLE
Journeys Pages - needs wireframes and examples

### ISSUE THREAD

**Issue by ardeay** [zesty-io/app-google-analytics#19]

**Comment by ardeay** [comment]
![Image](https://user-images.githubusercontent.com/729972/177804285-7ad99cec-d33a-495a-8e32-cac2adbff9e7.png)

**Comment by ardeay** [comment]
![image](https://user-images.githubusercontent.com/729972/181260578-a8bfa460-a639-4347-a880-3d8b478833d7.png)

**Comment by ardeay** [comment]
@allenpigar for tomorrows work, have dropdown for entrances (urls), and when a entrance url is chosen, slice to match the entrance path

**Comment by allenpigar** [comment]
- Added journey tab.
- Added Entrance Dropdown Feature 
- Added Page Slice selection.
![journey_page](https://user-images.githubusercontent.com/50983144/182377157-6afce1ba-24ab-4033-8104-48a48aed5ab5.gif)
