### ISSUE TITLE
Port Existing Google Analytics App

### ISSUE THREAD

**Issue by ardeay** [zesty-io/app-google-analytics#2]
Port the code from the manager-ui application here https://github.com/zesty-io/manager-ui/tree/master/src/apps/reports/src/app/views/Analytics

This will be the start of the application

![Image](https://user-images.githubusercontent.com/729972/172624634-549b52b1-7111-4574-862d-ee8b5f37e7d7.png)

**Comment by giseleblair** [comment]
The existing GA app does not use the latest version of GA. Please be sure to implement for GA4.
