### ISSUE TITLE
Journey: Business intelligence breakdown 

### ISSUE THREAD

**Issue by ardeay** [zesty-io/app-google-analytics#27]
Automate a sentence like "The top page "page name" from the "page name" entrance received 84 visits (25%) of traffic flow. 

put sentence to top of the experience below "last 7 days"

![image](https://user-images.githubusercontent.com/729972/181822254-f5b5260c-f805-45b5-8e40-ec9ea363b002.png)

**Comment by allenpigar** [comment]
Added automated sentence for the summary of top pages.
![summary tab](https://user-images.githubusercontent.com/50983144/182377390-e5b43794-4026-44e2-b061-592db7df8a4c.gif)
