### ISSUE TITLE
analytics: error timeout

### ISSUE THREAD

**Issue by darwin808** [zesty-io/app-google-analytics#32]
https://console.cloud.google.com/errors/detail/CLXTy4S8j96nVg;time=PT1H?project=zesty-prod

![Image](https://github.com/zesty-io/app-google-analytics-ua/assets/71545960/bf4bd9af-a450-4916-86af-1a0e271d9b14)

@allenpigar

**Comment by allenpigar** [comment]
@darwin808 i have moved this issue on the analytics-api repository.

https://github.com/zesty-io/analytics-api/issues/13
