### ISSUE TITLE
Overview page

### ISSUE THREAD

**Issue by ardeay** [zesty-io/app-google-analytics#5]
This is the page already created in manager-ui https://github.com/zesty-io/manager-ui/tree/master/src/apps/reports/src/app/views/Analytics

![Image](https://user-images.githubusercontent.com/729972/172627202-8f3319c5-7703-423c-98e0-3bf1f59827f3.png)

**Comment by allenpigar** [comment]
New Overview Page.

![image](https://user-images.githubusercontent.com/50983144/177197298-ea58f0b5-896c-4217-8b36-43910942b349.png)
