### ISSUE TITLE
Setup Test Env Value - Test GA Data Endpoint

### ISSUE THREAD

**Issue by ardeay** [zesty-io/app-google-analytics#6]
Test values (authentication and instance ZUID) will be needed to test the application locally (local env file)

Verify the Cloud Function connects to Google Analytics API https://github.com/zesty-io/gcp-cf/tree/master/googleAnalyticsGetPageViews

Deployed to https://us-central1-zesty-prod.cloudfunctions.net/googleAnalyticsGetPageViews

Example 

```
curl --location --request POST 'https://us-central1-zesty-prod.cloudfunctions.net/googleAnalyticsGetPageViews?zuid=8-aaeffee09b-7w6v22' \
--header 'Content-Type: text/plain' \
--data-raw ' {
	"gaRequest":{
	  "reportRequests":[
		  {
		    "viewId":"103227557",
		    "dateRanges": [{"startDate": "30daysAgo", "endDate": "today"}],
		    "metrics":[{"expression":"ga:newUsers"}],
		    "dimensions": [{"name":"ga:sessionCount"}]
		    }
		]
	},
	"type": "bar"
}
'
```

**Comment by allenpigar** [comment]
API is working properly on local env. 

curl --location --request POST 'http://localhost:7373/getPageViewData?zuid=8-45a294a-btwkv9' \
--header 'Content-Type: application/json' \
--data-raw ' {
	"gaRequest":{
	  "reportRequests":[
		  {
		    "viewId":"269536376",
		    "dateRanges": [{"startDate": "2022-06-01", "endDate": "2022-06-22"}],
		    "metrics":[{"expression":"ga:newUsers"}],
		    "dimensions": [{"name":"ga:sessionCount"}]
		    }
		]
	},
	"type": "bar"
}
'
_______________________________________________________________________________________

![image](https://user-images.githubusercontent.com/50983144/174876495-ae76384f-73cb-42e9-a93c-8ba2717ee165.png)


Return Value :

{
    "chartJSData": {
        "labels": [
            "1"
        ],
        "datasets": [
            {
                "label": "NewUsers",
                "data": [
                    "2"
                ],
                "backgroundColor": "rgba(122,86,255,0.9)"
            }
        ]
    },
    "tableData": {
        "headers": [
            "SessionCount",
            "NewUsers"
        ],
        "data": [
            [
                "1",
                "2"
            ]
        ]
    },
    "googleData": {
        "reports": [
            {
                "columnHeader": {
                    "dimensions": [
                        "ga:sessionCount"
                    ],
                    "metricHeader": {
                        "metricHeaderEntries": [
                            {
                                "name": "ga:newUsers",
                                "type": "INTEGER"
                            }
                        ]
                    }
                },
                "data": {
                    "rows": [
                        {
                            "dimensions": [
                                "1"
                            ],
                            "metrics": [
                                {
                                    "values": [
                                        "2"
                                    ]
                                }
                            ]
                        }
                    ],
                    "totals": [
                        {
                            "values": [
                                "2"
                            ]
                        }
                    ],
                    "rowCount": 1,
                    "minimums": [
                        {
                            "values": [
                                "2"
                            ]
                        }
                    ],
                    "maximums": [
                        {
                            "values": [
                                "2"
                            ]
                        }
                    ]
                }
            }
        ]
    }
}

**Comment by allenpigar** [comment]
API is working locally.  

![image](https://user-images.githubusercontent.com/50983144/174876698-fe88f52a-e848-4acc-ae25-259132a1305d.png)
